/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	demov1 "github.com/bwarminski/brett-custom-resource/pkg/apis/demo/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExternalWatchers implements ExternalWatcherInterface
type FakeExternalWatchers struct {
	Fake *FakeBwarminskiV1
	ns   string
}

var externalwatchersResource = schema.GroupVersionResource{Group: "bwarminski.com", Version: "v1", Resource: "externalwatchers"}

var externalwatchersKind = schema.GroupVersionKind{Group: "bwarminski.com", Version: "v1", Kind: "ExternalWatcher"}

// Get takes name of the externalWatcher, and returns the corresponding externalWatcher object, and an error if there is any.
func (c *FakeExternalWatchers) Get(name string, options v1.GetOptions) (result *demov1.ExternalWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(externalwatchersResource, c.ns, name), &demov1.ExternalWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.ExternalWatcher), err
}

// List takes label and field selectors, and returns the list of ExternalWatchers that match those selectors.
func (c *FakeExternalWatchers) List(opts v1.ListOptions) (result *demov1.ExternalWatcherList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(externalwatchersResource, externalwatchersKind, c.ns, opts), &demov1.ExternalWatcherList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &demov1.ExternalWatcherList{ListMeta: obj.(*demov1.ExternalWatcherList).ListMeta}
	for _, item := range obj.(*demov1.ExternalWatcherList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested externalWatchers.
func (c *FakeExternalWatchers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(externalwatchersResource, c.ns, opts))

}

// Create takes the representation of a externalWatcher and creates it.  Returns the server's representation of the externalWatcher, and an error, if there is any.
func (c *FakeExternalWatchers) Create(externalWatcher *demov1.ExternalWatcher) (result *demov1.ExternalWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(externalwatchersResource, c.ns, externalWatcher), &demov1.ExternalWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.ExternalWatcher), err
}

// Update takes the representation of a externalWatcher and updates it. Returns the server's representation of the externalWatcher, and an error, if there is any.
func (c *FakeExternalWatchers) Update(externalWatcher *demov1.ExternalWatcher) (result *demov1.ExternalWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(externalwatchersResource, c.ns, externalWatcher), &demov1.ExternalWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.ExternalWatcher), err
}

// Delete takes name of the externalWatcher and deletes it. Returns an error if one occurs.
func (c *FakeExternalWatchers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(externalwatchersResource, c.ns, name), &demov1.ExternalWatcher{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExternalWatchers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(externalwatchersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &demov1.ExternalWatcherList{})
	return err
}

// Patch applies the patch and returns the patched externalWatcher.
func (c *FakeExternalWatchers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *demov1.ExternalWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(externalwatchersResource, c.ns, name, data, subresources...), &demov1.ExternalWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.ExternalWatcher), err
}
