/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	demov1 "github.com/bwarminski/brett-custom-resource/pkg/apis/demo/v1"
	versioned "github.com/bwarminski/brett-custom-resource/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bwarminski/brett-custom-resource/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/bwarminski/brett-custom-resource/pkg/client/listers/demo/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ExternalWatcherInformer provides access to a shared informer and lister for
// ExternalWatchers.
type ExternalWatcherInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ExternalWatcherLister
}

type externalWatcherInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewExternalWatcherInformer constructs a new informer for ExternalWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewExternalWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredExternalWatcherInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredExternalWatcherInformer constructs a new informer for ExternalWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredExternalWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BwarminskiV1().ExternalWatchers(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BwarminskiV1().ExternalWatchers(namespace).Watch(options)
			},
		},
		&demov1.ExternalWatcher{},
		resyncPeriod,
		indexers,
	)
}

func (f *externalWatcherInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredExternalWatcherInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *externalWatcherInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&demov1.ExternalWatcher{}, f.defaultInformer)
}

func (f *externalWatcherInformer) Lister() v1.ExternalWatcherLister {
	return v1.NewExternalWatcherLister(f.Informer().GetIndexer())
}
