/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	brettdeploymentv1 "github.com/bwarminski/brett-custom-resource/deployment/pkg/apis/brettdeployment/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBrettDeployments implements BrettDeploymentInterface
type FakeBrettDeployments struct {
	Fake *FakeBwarminskiV1
	ns   string
}

var brettdeploymentsResource = schema.GroupVersionResource{Group: "bwarminski.com", Version: "v1", Resource: "brettdeployments"}

var brettdeploymentsKind = schema.GroupVersionKind{Group: "bwarminski.com", Version: "v1", Kind: "BrettDeployment"}

// Get takes name of the brettDeployment, and returns the corresponding brettDeployment object, and an error if there is any.
func (c *FakeBrettDeployments) Get(name string, options v1.GetOptions) (result *brettdeploymentv1.BrettDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(brettdeploymentsResource, c.ns, name), &brettdeploymentv1.BrettDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*brettdeploymentv1.BrettDeployment), err
}

// List takes label and field selectors, and returns the list of BrettDeployments that match those selectors.
func (c *FakeBrettDeployments) List(opts v1.ListOptions) (result *brettdeploymentv1.BrettDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(brettdeploymentsResource, brettdeploymentsKind, c.ns, opts), &brettdeploymentv1.BrettDeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &brettdeploymentv1.BrettDeploymentList{ListMeta: obj.(*brettdeploymentv1.BrettDeploymentList).ListMeta}
	for _, item := range obj.(*brettdeploymentv1.BrettDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested brettDeployments.
func (c *FakeBrettDeployments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(brettdeploymentsResource, c.ns, opts))

}

// Create takes the representation of a brettDeployment and creates it.  Returns the server's representation of the brettDeployment, and an error, if there is any.
func (c *FakeBrettDeployments) Create(brettDeployment *brettdeploymentv1.BrettDeployment) (result *brettdeploymentv1.BrettDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(brettdeploymentsResource, c.ns, brettDeployment), &brettdeploymentv1.BrettDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*brettdeploymentv1.BrettDeployment), err
}

// Update takes the representation of a brettDeployment and updates it. Returns the server's representation of the brettDeployment, and an error, if there is any.
func (c *FakeBrettDeployments) Update(brettDeployment *brettdeploymentv1.BrettDeployment) (result *brettdeploymentv1.BrettDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(brettdeploymentsResource, c.ns, brettDeployment), &brettdeploymentv1.BrettDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*brettdeploymentv1.BrettDeployment), err
}

// Delete takes name of the brettDeployment and deletes it. Returns an error if one occurs.
func (c *FakeBrettDeployments) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(brettdeploymentsResource, c.ns, name), &brettdeploymentv1.BrettDeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBrettDeployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(brettdeploymentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &brettdeploymentv1.BrettDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched brettDeployment.
func (c *FakeBrettDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *brettdeploymentv1.BrettDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(brettdeploymentsResource, c.ns, name, data, subresources...), &brettdeploymentv1.BrettDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*brettdeploymentv1.BrettDeployment), err
}
