/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/bwarminski/brett-custom-resource/deployment/pkg/apis/brettdeployment/v1"
	scheme "github.com/bwarminski/brett-custom-resource/deployment/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BrettDeploymentsGetter has a method to return a BrettDeploymentInterface.
// A group's client should implement this interface.
type BrettDeploymentsGetter interface {
	BrettDeployments(namespace string) BrettDeploymentInterface
}

// BrettDeploymentInterface has methods to work with BrettDeployment resources.
type BrettDeploymentInterface interface {
	Create(*v1.BrettDeployment) (*v1.BrettDeployment, error)
	Update(*v1.BrettDeployment) (*v1.BrettDeployment, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.BrettDeployment, error)
	List(opts metav1.ListOptions) (*v1.BrettDeploymentList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.BrettDeployment, err error)
	BrettDeploymentExpansion
}

// brettDeployments implements BrettDeploymentInterface
type brettDeployments struct {
	client rest.Interface
	ns     string
}

// newBrettDeployments returns a BrettDeployments
func newBrettDeployments(c *BwarminskiV1Client, namespace string) *brettDeployments {
	return &brettDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the brettDeployment, and returns the corresponding brettDeployment object, and an error if there is any.
func (c *brettDeployments) Get(name string, options metav1.GetOptions) (result *v1.BrettDeployment, err error) {
	result = &v1.BrettDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("brettdeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BrettDeployments that match those selectors.
func (c *brettDeployments) List(opts metav1.ListOptions) (result *v1.BrettDeploymentList, err error) {
	result = &v1.BrettDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("brettdeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested brettDeployments.
func (c *brettDeployments) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("brettdeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a brettDeployment and creates it.  Returns the server's representation of the brettDeployment, and an error, if there is any.
func (c *brettDeployments) Create(brettDeployment *v1.BrettDeployment) (result *v1.BrettDeployment, err error) {
	result = &v1.BrettDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("brettdeployments").
		Body(brettDeployment).
		Do().
		Into(result)
	return
}

// Update takes the representation of a brettDeployment and updates it. Returns the server's representation of the brettDeployment, and an error, if there is any.
func (c *brettDeployments) Update(brettDeployment *v1.BrettDeployment) (result *v1.BrettDeployment, err error) {
	result = &v1.BrettDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("brettdeployments").
		Name(brettDeployment.Name).
		Body(brettDeployment).
		Do().
		Into(result)
	return
}

// Delete takes name of the brettDeployment and deletes it. Returns an error if one occurs.
func (c *brettDeployments) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("brettdeployments").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *brettDeployments) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("brettdeployments").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched brettDeployment.
func (c *brettDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.BrettDeployment, err error) {
	result = &v1.BrettDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("brettdeployments").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
