/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	brettdeploymentv1 "github.com/bwarminski/brett-custom-resource/deployment/pkg/apis/brettdeployment/v1"
	versioned "github.com/bwarminski/brett-custom-resource/deployment/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bwarminski/brett-custom-resource/deployment/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/bwarminski/brett-custom-resource/deployment/pkg/client/listers/brettdeployment/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BrettDeploymentInformer provides access to a shared informer and lister for
// BrettDeployments.
type BrettDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BrettDeploymentLister
}

type brettDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBrettDeploymentInformer constructs a new informer for BrettDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBrettDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBrettDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBrettDeploymentInformer constructs a new informer for BrettDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBrettDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BwarminskiV1().BrettDeployments(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BwarminskiV1().BrettDeployments(namespace).Watch(options)
			},
		},
		&brettdeploymentv1.BrettDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *brettDeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBrettDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *brettDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&brettdeploymentv1.BrettDeployment{}, f.defaultInformer)
}

func (f *brettDeploymentInformer) Lister() v1.BrettDeploymentLister {
	return v1.NewBrettDeploymentLister(f.Informer().GetIndexer())
}
